const countries = [
    'auburn, Alabama, United States',
    'birmingham, Alabama, United States',
    'dothan, Alabama, United States',
    'florence / muscle shoals, Alabama, United States',
    'gadsden-anniston, Alabama, United States',
    'huntsville / decatur, Alabama, United States',
    'mobile, Alabama, United States',
    'montgomery, Alabama, United States',
    'tuscaloosa, Alabama, United States',
    // here
    'anchorage / mat-su, Alaska, United States',
    'fairbanks, Alaska, United States',
    'kenai peninsula, Alaska, United States',
    'southeast alaska, Alaska, United States',
    'flagstaff / sedona, Arizona, United States',
    'mohave county, Arizona, United States',
    'phoenix, Arizona, United States',
    'prescott, Arizona, United States',
    'show low, Arizona, United States',
    'sierra vista, Arizona, United States',
    'tucson, Arizona, United States',
    'yuma, Arizona, United States',
    'fayetteville, Arkansas, United States',
    'fort smith, Arkansas, United States',
    'jonesboro, Arkansas, United States',
    'little rock, Arkansas, United States',
    'texarkana, Arkansas, United States',
    'bakersfield, California, United States',
    'chico, California, United States',
    'fresno / madera, California, United States',
    'gold country, California, United States',
    'hanford-corcoran, California, United States',
    'humboldt county, California, United States',
    'imperial county, California, United States',
    'inland empire, California, United States',
    'los angeles, California, United States',
    'mendocino county, California, United States',
    'merced, California, United States',
    'modesto, California, United States',
    'monterey bay, California, United States',
    'orange county, California, United States',
    'palm springs, California, United States',
    'redding, California, United States',
    'sacramento, California, United States',
    'san diego, California, United States',
    'san francisco bay area, California, United States',
    'san luis obispo, California, United States',
    'santa barbara, California, United States',
    'santa maria, California, United States',
    'siskiyou county, California, United States',
    'stockton, California, United States',
    'susanville, California, United States',
    'ventura county, California, United States',
    'visalia-tulare, California, United States',
    'yuba-sutter, California, United States',
    'boulder, Colorado, United States',
    'colorado springs, Colorado, United States',
    'denver, Colorado, United States',
    'eastern CO, Colorado, United States',
    'fort collins / north CO, Colorado, United States',
    'high rockies, Colorado, United States',
    'pueblo, Colorado, United States',
    'western slope, Colorado, United States',
    'eastern CT, Connecticut, United States',
    'hartford, Connecticut, United States',
    'new haven, Connecticut, United States',
    'northwest CT, Connecticut, United States',
    'delaware, Delaware, United States',
    'washington, District of Columbia, United States',
    'broward county, Florida, United States',
    'daytona beach, Florida, United States',
    'florida keys, Florida, United States',
    'fort lauderdale, Florida, United States',
    'ft myers / SW florida, Florida, United States',
    'gainesville, Florida, United States',
    'heartland florida, Florida, United States',
    'jacksonville, Florida, United States',
    'lakeland, Florida, United States',
    'miami / dade, Florida, United States',
    'north central FL, Florida, United States',
    'ocala, Florida, United States',
    'okaloosa / walton, Florida, United States',
    'orlando, Florida, United States',
    'panama city, Florida, United States',
    'pensacola, Florida, United States',
    'sarasota-bradenton, Florida, United States',
    'south florida, Florida, United States',
    'space coast, Florida, United States',
    'st augustine, Florida, United States',
    'tallahassee, Florida, United States',
    'tampa bay area, Florida, United States',
    'treasure coast, Florida, United States',
    'palm beach county, Florida, United States',
    'albany, Georgia, United States',
    'athens, Georgia, United States',
    'atlanta, Georgia, United States',
    'augusta, Georgia, United States',
    'brunswick, Georgia, United States',
    'columbus, Georgia, United States',
    'macon / warner robins, Georgia, United States',
    'northwest GA, Georgia, United States',
    'savannah / hinesville, Georgia, United States',
    'statesboro, Georgia, United States',
    'valdosta, Georgia, United States',
    'hawaii, Hawaii, United States',
    'boise, Idaho, United States',
    'east idaho, Idaho, United States',
    'lewiston / clarkston, Idaho, United States',
    'twin falls, Idaho, United States',
    'bloomington-normal, Illinois, United States',
    'champaign urbana, Illinois, United States',
    'chicago, Illinois, United States',
    'decatur, Illinois, United States',
    'la salle co, Illinois, United States',
    'mattoon-charleston, Illinois, United States',
    'peoria, Illinois, United States',
    'rockford, Illinois, United States',
    'southern illinois, Illinois, United States',
    'springfield, Illinois, United States',
    'western IL, Illinois, United States',
    'bloomington, Indiana, United States',
    'evansville, Indiana, United States',
    'fort wayne, Indiana, United States',
    'indianapolis, Indiana, United States',
    'kokomo, Indiana, United States',
    'lafayette / west lafayette, Indiana, United States',
    'muncie / anderson, Indiana, United States',
    'richmond, Indiana, United States',
    'south bend / michiana, Indiana, United States',
    'terre haute, Indiana, United States',
    'ames, Iowa, United States',
    'cedar rapids, Iowa, United States',
    'des moines, Iowa, United States',
    'dubuque, Iowa, United States',
    'fort dodge, Iowa, United States',
    'iowa city, Iowa, United States',
    'mason city, Iowa, United States',
    'quad cities, Iowa, United States',
    'sioux city, Iowa, United States',
    'southeast IA, Iowa, United States',
    'waterloo / cedar falls, Iowa, United States',
    'lawrence, Kansas, United States',
    'manhattan, Kansas, United States',
    'northwest KS, Kansas, United States',
    'salina, Kansas, United States',
    'southeast KS, Kansas, United States',
    'southwest KS, Kansas, United States',
    'topeka, Kansas, United States',
    'wichita, Kansas, United States',
    'bowling green, Kentucky, United States',
    'eastern kentucky, Kentucky, United States',
    'lexington, Kentucky, United States',
    'louisville, Kentucky, United States',
    'owensboro, Kentucky, United States',
    'western KY, Kentucky, United States',
    'baton rouge, Louisiana, United States',
    'central louisiana, Louisiana, United States',
    'houma, Louisiana, United States',
    'lafayette, Louisiana, United States',
    'lake charles, Louisiana, United States',
    'monroe, Louisiana, United States',
    'new orleans, Louisiana, United States',
    'shreveport, Louisiana, United States',
    'maine, Maine, United States',
    'annapolis, Maryland, United States',
    'baltimore, Maryland, United States',
    'eastern shore, Maryland, United States',
    'frederick, Maryland, United States',
    'southern maryland, Maryland, United States',
    'western maryland, Maryland, United States',
    'boston, Massachusetts, United States',
    'cape cod / islands, Massachusetts, United States',
    'south coast, Massachusetts, United States',
    'western massachusetts, Massachusetts, United States',
    'worcester / central MA, Massachusetts, United States',
    'ann arbor, Michigan, United States',
    'battle creek, Michigan, United States',
    'central michigan, Michigan, United States',
    'detroit metro, Michigan, United States',
    'flint, Michigan, United States',
    'grand rapids, Michigan, United States',
    'holland, Michigan, United States',
    'jackson, Michigan, United States',
    'kalamazoo, Michigan, United States',
    'lansing, Michigan, United States',
    'monroe, Michigan, United States',
    'muskegon, Michigan, United States',
    'northern michigan, Michigan, United States',
    'port huron, Michigan, United States',
    'saginaw-midland-baycity, Michigan, United States',
    'southwest michigan, Michigan, United States',
    'the thumb, Michigan, United States',
    'upper peninsula, Michigan, United States',
    'bemidji, Minnesota, United States',
    'brainerd, Minnesota, United States',
    'duluth / superior, Minnesota, United States',
    'mankato, Minnesota, United States',
    'minneapolis / st paul, Minnesota, United States',
    'rochester, Minnesota, United States',
    'southwest MN, Minnesota, United States',
    'st cloud, Minnesota, United States',
    'gulfport / biloxi, Mississippi, United States',
    'hattiesburg, Mississippi, United States',
    'jackson, Mississippi, United States',
    'meridian, Mississippi, United States',
    'north mississippi, Mississippi, United States',
    'southwest MS, Mississippi, United States',
    'columbia / jeff city, Missouri, United States',
    'joplin, Missouri, United States',
    'kansas city, Missouri, United States',
    'kirksville, Missouri, United States',
    'lake of the ozarks, Missouri, United States',
    'southeast missouri, Missouri, United States',
    'springfield, Missouri, United States',
    'st joseph, Missouri, United States',
    'st louis, Missouri, United States',
    'billings, Montana, United States',
    'bozeman, Montana, United States',
    'butte, Montana, United States',
    'great falls, Montana, United States',
    'helena, Montana, United States',
    'kalispell, Montana, United States',
    'missoula, Montana, United States',
    'eastern montana, Montana, United States',
    'grand island, Nebraska, United States',
    'lincoln, Nebraska, United States',
    'north platte, Nebraska, United States',
    'omaha / council bluffs, Nebraska, United States',
    'scottsbluff / panhandle, Nebraska, United States',
    'elko, Nevada, United States',
    'las vegas, Nevada, United States',
    'reno / tahoe, Nevada, United States',
    'new hampshire, New Hampshire, United States',
    'central NJ, New Jersey, United States',
    'jersey shore, New Jersey, United States',
    'north jersey, New Jersey, United States',
    'south jersey, New Jersey, United States',
    'albuquerque, New Mexico, United States',
    'clovis / portales, New Mexico, United States',
    'farmington, New Mexico, United States',
    'las cruces, New Mexico, United States',
    'roswell / carlsbad, New Mexico, United States',
    'santa fe / taos, New Mexico, United States',
    'albany, New York, United States',
    'binghamton, New York, United States',
    'buffalo, New York, United States',
    'catskills, New York, United States',
    'chautauqua, New York, United States',
    'elmira-corning, New York, United States',
    'finger lakes, New York, United States',
    'glens falls, New York, United States',
    'hudson valley, New York, United States',
    'ithaca, New York, United States',
    'long island, New York, United States',
    'new york city, New York, United States',
    'oneonta, New York, United States',
    'plattsburgh-adirondacks, New York, United States',
    'potsdam-canton-massena, New York, United States',
    'rochester, New York, United States',
    'syracuse, New York, United States',
    'twin tiers NY/PA, New York, United States',
    'utica-rome-oneida, New York, United States',
    'watertown, New York, United States',
    'asheville, North Carolina, United States',
    'boone, North Carolina, United States',
    'charlotte, North Carolina, United States',
    'eastern NC, North Carolina, United States',
    'fayetteville, North Carolina, United States',
    'greensboro, North Carolina, United States',
    'hickory / lenoir, North Carolina, United States',
    'jacksonville, North Carolina, United States',
    'outer banks, North Carolina, United States',
    'raleigh / durham / CH, North Carolina, United States',
    'wilmington, North Carolina, United States',
    'winston-salem, North Carolina, United States',
    'bismarck, North Dakota, United States',
    'fargo / moorhead, North Dakota, United States',
    'grand forks, North Dakota, United States',
    'north dakota, North Dakota, United States',
    'akron / canton, Ohio, United States',
    'ashtabula, Ohio, United States',
    'athens, Ohio, United States',
    'chillicothe, Ohio, United States',
    'cincinnati, Ohio, United States',
    'cleveland, Ohio, United States',
    'columbus, Ohio, United States',
    'dayton / springfield, Ohio, United States',
    'lima / findlay, Ohio, United States',
    'mansfield, Ohio, United States',
    'sandusky, Ohio, United States',
    'toledo, Ohio, United States',
    'tuscarawas co, Ohio, United States',
    'youngstown, Ohio, United States',
    'zanesville / cambridge, Ohio, United States',
    'lawton, Oklahoma, United States',
    'northwest OK, Oklahoma, United States',
    'oklahoma city, Oklahoma, United States',
    'stillwater, Oklahoma, United States',
    'tulsa, Oklahoma, United States',
    'bend, Oregon, United States',
    'corvallis/albany, Oregon, United States',
    'east oregon, Oregon, United States',
    'eugene, Oregon, United States',
    'klamath falls, Oregon, United States',
    'medford-ashland, Oregon, United States',
    'oregon coast, Oregon, United States',
    'portland, Oregon, United States',
    'roseburg, Oregon, United States',
    'salem, Oregon, United States',
    'altoona-johnstown, Pennsylvania, United States',
    'cumberland valley, Pennsylvania, United States',
    'erie, Pennsylvania, United States',
    'harrisburg, Pennsylvania, United States',
    'lancaster, Pennsylvania, United States',
    'lehigh valley, Pennsylvania, United States',
    'meadville, Pennsylvania, United States',
    'philadelphia, Pennsylvania, United States',
    'pittsburgh, Pennsylvania, United States',
    'poconos, Pennsylvania, United States',
    'reading, Pennsylvania, United States',
    'scranton / wilkes-barre, Pennsylvania, United States',
    'state college, Pennsylvania, United States',
    'williamsport, Pennsylvania, United States',
    'york, Pennsylvania, United States',
    'rhode island, Rhode Island, United States',
    'charleston, South Carolina, United States',
    'columbia, South Carolina, United States',
    'florence, South Carolina, United States',
    'greenville / upstate, South Carolina, United States',
    'hilton head, South Carolina, United States',
    'myrtle beach, South Carolina, United States',
    'northeast SD, South Dakota, United States',
    'pierre / central SD, South Dakota, United States',
    'rapid city / west SD, South Dakota, United States',
    'sioux falls / SE SD, South Dakota, United States',
    'south dakota, South Dakota, United States',
    'chattanooga, Tennessee, United States',
    'clarksville, Tennessee, United States',
    'cookeville, Tennessee, United States',
    'jackson, Tennessee, United States',
    'knoxville, Tennessee, United States',
    'memphis, Tennessee, United States',
    'nashville, Tennessee, United States',
    'tri-cities, Tennessee, United States',
    'abilene, Texas, United States',
    'amarillo, Texas, United States',
    'austin, Texas, United States',
    'beaumont / port arthur, Texas, United States',
    'brownsville, Texas, United States',
    'college station, Texas, United States',
    'corpus christi, Texas, United States',
    'dallas / fort worth, Texas, United States',
    'deep east texas, Texas, United States',
    'del rio / eagle pass, Texas, United States',
    'el paso, Texas, United States',
    'galveston, Texas, United States',
    'houston, Texas, United States',
    'killeen / temple / ft hood, Texas, United States',
    'laredo, Texas, United States',
    'lubbock, Texas, United States',
    'mcallen / edinburg, Texas, United States',
    'odessa / midland, Texas, United States',
    'san angelo, Texas, United States',
    'san antonio, Texas, United States',
    'san marcos, Texas, United States',
    'southwest TX, Texas, United States',
    'texoma, Texas, United States',
    'tyler / east TX, Texas, United States',
    'victoria, Texas, United States',
    'waco, Texas, United States',
    'wichita falls, Texas, United States',
    'logan, Utah, United States',
    'ogden-clearfield, Utah, United States',
    'provo / orem, Utah, United States',
    'salt lake city, Utah, United States',
    'st george, Utah, United States',
    'vermont, Vermont, United States',
    'charlottesville, Virginia, United States',
    'danville, Virginia, United States',
    'fredericksburg, Virginia, United States',
    'hampton roads, Virginia, United States',
    'harrisonburg, Virginia, United States',
    'lynchburg, Virginia, United States',
    'new river valley, Virginia, United States',
    'richmond, Virginia, United States',
    'roanoke, Virginia, United States',
    'southwest VA, Virginia, United States',
    'winchester, Virginia, United States',
    'bellingham, Washington, United States',
    'kennewick-pasco-richland, Washington, United States',
    'moses lake, Washington, United States',
    'olympic peninsula, Washington, United States',
    'pullman / moscow, Washington, United States',
    'seattle-tacoma, Washington, United States',
    'skagit / island / SJI, Washington, United States',
    `spokane / coeur d'alene, Washington, United States`,
    'wenatchee, Washington, United States',
    'yakima, Washington, United States',
    'charleston, West Virginia, United States',
    'eastern panhandle, West Virginia, United States',
    'huntington-ashland, West Virginia, United States',
    'morgantown, West Virginia, United States',
    'northern panhandle, West Virginia, United States',
    'parkersburg-marietta, West Virginia, United States',
    'southern WV, West Virginia, United States',
    'west virginia (old), West Virginia, United States',
    'appleton-oshkosh-FDL, Wisconsin, United States',
    'eau claire, Wisconsin, United States',
    'green bay, Wisconsin, United States',
    'janesville, Wisconsin, United States',
    'kenosha-racine, Wisconsin, United States',
    'la crosse, Wisconsin, United States',
    'madison, Wisconsin, United States',
    'milwaukee, Wisconsin, United States',
    'northern WI, Wisconsin, United States',
    'sheboygan, Wisconsin, United States',
    'wausau, Wisconsin, United States',
    'wyoming, Wyoming, United States',
    'guam-micronesia, , United States',
    'puerto rico, , United States',
    'U.S. virgin islands, , United States',
    'calgary, Alberta, Canada',
    'edmonton, Alberta, Canada',
    'ft mcmurray, Alberta, Canada',
    'lethbridge, Alberta, Canada',
    'medicine hat, Alberta, Canada',
    'peace river country, Alberta, Canada',
    'red deer, Alberta, Canada',
    'cariboo, British Columbia, Canada',
    'comox valley, British Columbia, Canada',
    'fraser valley, British Columbia, Canada',
    'kamloops, British Columbia, Canada',
    'kelowna / okanagan, British Columbia, Canada',
    'kootenays, British Columbia, Canada',
    'nanaimo, British Columbia, Canada',
    'prince george, British Columbia, Canada',
    'skeena-bulkley, British Columbia, Canada',
    'sunshine coast, British Columbia, Canada',
    'vancouver, British Columbia, Canada',
    'victoria, British Columbia, Canada',
    'whistler, British Columbia, Canada',
    'winnipeg, Manitoba, Canada',
    'new brunswick, New Brunswick, Canada',
    `st john's, Newfoundland and Labrador, Canada`,
    'territories, Northwest Territories, Canada',
    'yellowknife, Northwest Territories, Canada',
    'halifax, Nova Scotia, Canada',
    'barrie, Ontario, Canada',
    'belleville, Ontario, Canada',
    'brantford-woodstock, Ontario, Canada',
    'chatham-kent, Ontario, Canada',
    'cornwall, Ontario, Canada',
    'guelph, Ontario, Canada',
    'hamilton-burlington, Ontario, Canada',
    'kingston, Ontario, Canada',
    'kitchener-waterloo-cambridge, Ontario, Canada',
    'london, Ontario, Canada',
    'niagara region, Ontario, Canada',
    'ottawa-hull-gatineau, Ontario, Canada',
    'owen sound, Ontario, Canada',
    'peterborough, Ontario, Canada',
    'sarnia, Ontario, Canada',
    'sault ste marie, Ontario, Canada',
    'sudbury, Ontario, Canada',
    'thunder bay, Ontario, Canada',
    'toronto, Ontario, Canada',
    'windsor, Ontario, Canada',
    'prince edward island, Prince Edward Island, Canada',
    'montreal, Quebec, Canada',
    'quebec city, Quebec, Canada',
    'saguenay, Quebec, Canada',
    'sherbrooke, Quebec, Canada',
    'trois-rivieres, Quebec, Canada',
    'regina, Saskatchewan, Canada',
    'saskatoon, Saskatchewan, Canada',
    'whitehorse, Yukon Territory, Canada',
    'vienna, Austria',
    'belgium, Belguim',
    'bulgaria, Bulgaria',
    'croatia, Croatia',
    'prague, Czech Republic',
    'copenhagen, Denmark',
    'finland, Finland',
    'bordeaux, France',
    'brittany, France',
    'grenoble, France',
    'lille, France',
    'loire valley, France',
    'lyon, France',
    'marseille, France',
    'montpellier, France',
    `nice / cote d'azur, France`,
    'normandy, France',
    'paris, France',
    'strasbourg, France',
    'toulouse, France',
    'berlin, Germany',
    'bremen, Germany',
    'cologne, Germany',
    'dresden, Germany',
    'dusseldorf, Germany',
    'essen / ruhr, Germany',
    'frankfurt, Germany',
    'hamburg, Germany',
    'hannover, Germany',
    'heidelberg, Germany',
    'kaiserslautern, Germany',
    'leipzig, Germany',
    'munich, Germany',
    'nuremberg, Germany',
    'stuttgart, Germany',
    'greece, Greece',
    'budapest, Hungary',
    'reykjavik, Iceland',
    'dublin, Ireland',
    'bologna, Italy',
    'florence / tuscany, Italy',
    'genoa, Italy',
    'milan, Italy',
    'napoli / campania, Italy',
    'perugia, Italy',
    'rome, Italy',
    'sardinia, Italy',
    'sicilia, Italy',
    'torino, Italy',
    'venice / veneto, Italy',
    'luxembourg, Luxembourg',
    'amsterdam / randstad, Netherlands',
    'norway, Norway',
    'poland, Poland',
    'faro / algarve, Portugal',
    'lisbon, Portugal',
    'porto, Portugal',
    'romania, Romania',
    'moscow, Russian Federation',
    'st petersburg, Russian Federation',
    'alicante, Spain',
    'baleares, Spain',
    'barcelona, Spain',
    'bilbao, Spain',
    'cadiz, Spain',
    'canarias, Spain',
    'granada, Spain',
    'madrid, Spain',
    'malaga, Spain',
    'sevilla, Spain',
    'valencia, Spain',
    'sweden, Sweden',
    'basel, Switzerland',
    'bern, Switzerland',
    'geneva, Switzerland',
    'lausanne, Switzerland',
    'zurich, Switzerland',
    'turkey, Turkey',
    'ukraine, Ukraine',
    'aberdeen, United Kingdom',
    'bath, United Kingdom',
    'belfast, United Kingdom',
    'birmingham / west mids, United Kingdom',
    'brighton, United Kingdom',
    'bristol, United Kingdom',
    'cambridge, UK, United Kingdom',
    'cardiff / wales, United Kingdom',
    'coventry, United Kingdom',
    'derby, United Kingdom',
    'devon & cornwall, United Kingdom',
    'dundee, United Kingdom',
    'east anglia, United Kingdom',
    'east midlands, United Kingdom',
    'edinburgh, United Kingdom',
    'essex, United Kingdom',
    'glasgow, United Kingdom',
    'hampshire, United Kingdom',
    'kent, United Kingdom',
    'leeds, United Kingdom',
    'liverpool, United Kingdom',
    'london, United Kingdom',
    'manchester, United Kingdom',
    'newcastle / NE england, United Kingdom',
    'nottingham, United Kingdom',
    'oxford, United Kingdom',
    'sheffield, United Kingdom',
    'bangladesh, Bangladesh',
    'beijing, China',
    'chengdu, China',
    'chongqing, China',
    'dalian, China',
    'guangzhou, China',
    'hangzhou, China',
    'nanjing, China',
    'shanghai, China',
    'shenyang, China',
    'shenzhen, China',
    'wuhan, China',
    `xi'an, China`,
    'guam-micronesia, Guam / Micronesia',
    'hong kong, Hong Kong',
    'ahmedabad, India',
    'bangalore, India',
    'bhubaneswar, India',
    'chandigarh, India',
    'chennai (madras), India',
    'delhi, India',
    'goa, India',
    'hyderabad, India',
    'indore, India',
    'jaipur, India',
    'kerala, India',
    'kolkata (calcutta), India',
    'lucknow, India',
    'mumbai, India',
    'pune, India',
    'surat surat, India',
    'indonesia, Indonesia',
    'iran, Iran',
    'iraq, Iraq',
    'Haifa, Israel',
    'jerusalem, Israel',
    'tel aviv, Israel',
    'west bank, Palestine',
    'fukuoka, Japan',
    'hiroshima, Japan',
    'nagoya, Japan',
    'okinawa, Japan',
    'osaka-kobe-kyoto, Japan',
    'sapporo, Japan',
    'sendai, Japan',
    'tokyo, Japan',
    'seoul, Korea',
    'kuwait, Kuwait',
    'beirut, Lebanon',
    'malaysia, Malaysia',
    'pakistan, Pakistan',
    'bacolod, Philippines',
    'bicol region, Philippines',
    'cagayan de oro, Philippines',
    'cebu, Philippines',
    'davao city, Philippines',
    'iloilo, Philippines',
    'manila, Philippines',
    'pampanga, Philippines',
    'zamboanga, Philippines',
    'singapore, Singapore',
    'taiwan, Taiwan',
    'thailand, Thailand',
    'united arab emirates, United Arab Emirates',
    'vietnam, Vietnam',
    'adelaide, Australia',
    'brisbane, Australia',
    'cairns, Australia',
    'canberra, Australia',
    'darwin, Australia',
    'gold coast, Australia',
    'melbourne, Australia',
    'newcastle, NSW, Australia',
    'perth, Australia',
    'sydney, Australia',
    'tasmania, Australia',
    'wollongong, Australia',
    'auckland, New Zealand',
    'christchurch, New Zealand',
    'dunedin, New Zealand',
    'wellington, New Zealand',
    'buenos aires, Argentina',
    'bolivia, Bolivia',
    'belo horizonte, Brazil',
    'brasilia, Brazil',
    'curitiba, Brazil',
    'fortaleza, Brazil',
    'porto alegre, Brazil',
    'recife, Brazil',
    'rio de janeiro, Brazil',
    'salvador, bahia, Brazil',
    'sao paulo, Brazil',
    'caribbean islands, Caribbean Islands',
    'chile, Chile',
    'colombia, Colombia',
    'costa rica, Costa Rica',
    'dominican republic, Dominican Republic',
    'ecuador, Ecuador',
    'el salvador, El Salvador',
    'guatemala, Guatemala',
    'acapulco, Mexico',
    'baja california sur, Mexico',
    'chihuahua, Mexico',
    'ciudad juarez, Mexico',
    'guadalajara, Mexico',
    'guanajuato, Mexico',
    'hermosillo, Mexico',
    'mazatlan, Mexico',
    'mexico city, Mexico',
    'monterrey, Mexico',
    'oaxaca, Mexico',
    'puebla, Mexico',
    'puerto vallarta, Mexico',
    'tijuana, Mexico',
    'veracruz, Mexico',
    'yucatan, Mexico',
    'nicaragua, Nicaragua',
    'panama, Panama',
    'peru, Peru',
    'puerto rico, Puerto Rico',
    'montevideo, Uruguay',
    'venezuela, Venezuela',
    'virgin islands, Virgin Islands',
    'egypt, Egypt',
    'ethiopia, Ethiopia',
    'ghana, Ghana',
    'kenya, Kenya',
    'morocco, Morocco',
    'cape town, South Africa',
    'durban, South Africa',
    'johannesburg, South Africa',
    'pretoria, South Africa',
    'tunisia, Tunisia'
]

function autocomplete(inp, arr) {
    /*the autocomplete function takes two arguments,
    the text field element and an array of possible autocompleted values:*/
    var currentFocus;
    /*execute a function when someone writes in the text field:*/
    inp.addEventListener("input", function(e) {
        var a, b, i, val = this.value;
        /*close any already open lists of autocompleted values*/
        closeAllLists();
        if (!val) { return false;}
        currentFocus = -1;
        /*create a DIV element that will contain the items (values):*/
        a = document.createElement("DIV");
        a.setAttribute("id", this.id + "autocomplete-list");
        a.setAttribute("class", "autocomplete-items");
        /*append the DIV element as a child of the autocomplete container:*/
        this.parentNode.appendChild(a);
        /*for each item in the array...*/
        for (i = 0; i < arr.length; i++) {
          /*check if the item starts with the same letters as the text field value:*/
          if (arr[i].substr(0, val.length).toUpperCase() == val.toUpperCase()) {
            /*create a DIV element for each matching element:*/
            b = document.createElement("DIV");
            /*make the matching letters bold:*/
            b.innerHTML = "<strong>" + arr[i].substr(0, val.length) + "</strong>";
            b.innerHTML += arr[i].substr(val.length);
            /*insert a input field that will hold the current array item's value:*/
            b.innerHTML += "<input type='hidden' value='" + arr[i] + "'>";
            /*execute a function when someone clicks on the item value (DIV element):*/
                b.addEventListener("click", function(e) {
                /*insert the value for the autocomplete text field:*/
                inp.value = this.getElementsByTagName("input")[0].value;
                /*close the list of autocompleted values,
                (or any other open lists of autocompleted values:*/
                closeAllLists();
            });
            a.appendChild(b);
          }
        }
    });
    /*execute a function presses a key on the keyboard:*/
    inp.addEventListener("keydown", function(e) {
        var x = document.getElementById(this.id + "autocomplete-list");
        if (x) x = x.getElementsByTagName("div");
        if (e.keyCode == 40) {
          /*If the arrow DOWN key is pressed,
          increase the currentFocus variable:*/
          currentFocus++;
          /*and and make the current item more visible:*/
          addActive(x);
        } else if (e.keyCode == 38) { //up
          /*If the arrow UP key is pressed,
          decrease the currentFocus variable:*/
          currentFocus--;
          /*and and make the current item more visible:*/
          addActive(x);
        } else if (e.keyCode == 13) {
          /*If the ENTER key is pressed, prevent the form from being submitted,*/
          e.preventDefault();
          if (currentFocus > -1) {
            /*and simulate a click on the "active" item:*/
            if (x) x[currentFocus].click();
          }
        }
    });
    function addActive(x) {
      /*a function to classify an item as "active":*/
      if (!x) return false;
      /*start by removing the "active" class on all items:*/
      removeActive(x);
      if (currentFocus >= x.length) currentFocus = 0;
      if (currentFocus < 0) currentFocus = (x.length - 1);
      /*add class "autocomplete-active":*/
      x[currentFocus].classList.add("autocomplete-active");
    }
    function removeActive(x) {
      /*a function to remove the "active" class from all autocomplete items:*/
      for (var i = 0; i < x.length; i++) {
        x[i].classList.remove("autocomplete-active");
      }
    }
    function closeAllLists(elmnt) {
      /*close all autocomplete lists in the document,
      except the one passed as an argument:*/
      var x = document.getElementsByClassName("autocomplete-items");
      for (var i = 0; i < x.length; i++) {
        if (elmnt != x[i] && elmnt != inp) {
        x[i].parentNode.removeChild(x[i]);
      }
    }
  }
  /*execute a function when someone clicks in the document:*/
  document.addEventListener("click", function (e) {
      closeAllLists(e.target);
  });
  }

  autocomplete(document.getElementById("myInput"), countries);